site_name: 自学教室
site_description: 中小学自学教室
# repo_name: vra/mkdocs-material-example
# repo_url: https://github.com/vra/mkdocs-material-example
copyright: Copyright &copy; 2024


nav:
  - 首页: index.md
  - 数学:
    - math/index.md
    - Installation: guide/installation.md
    - Basics: guide/basics.md
    - Configuration: guide/config.md
  - Changelog: changelog.md

theme:
  name: material
  language: zh
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: teal #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: cyan # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal #, [red, pink, purple, deep, purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue, grey, black, white]
      accent: cyan # [red, pink, purple, deep, purple, indigo, blue, light, blue, cyan, teal, green, light, green, lime, yellow, amber, orange, deep orange]
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

extra_css:
  - static/extra.css

extra_javascript:
  - js/tongji.js
